[package]
name = "pallet-executive-fuzzer"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Fuzz storage types of pallet-executive"
publish = false

[lints]
workspace = true

[[bin]]
name = "pallet-executive-fuzzer"
path = "src/fuzzer.rs"

[dependencies]
arbitrary = "1.3.2"
honggfuzz = "0.5.49"
frame-executive = { path = "..", default-features = false, features = ["std"] }
sp-runtime = { path = "../../../primitives/runtime", default-features = false }